server:
  port: 10086
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 30 # 间隔多少秒发一次心跳
    lease-expiration-duration-in-seconds: 90
  server:
    eviction-interval-timer-in-ms: 60000 #