server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vuejsdemo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: admin
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lss.user.pojo